# ==========================================
# كتالوج الخدمات والتطبيقات المدعومة
# ==========================================

SERVICES = {
    "wa": {"id": "whatsapp", "name": "واتساب WhatsApp", "icon": "🟢", "code": "wa", "fivesim_code": "whatsapp", "short": "WhatsApp"},
    "tg": {"id": "telegram", "name": "تيليجرام Telegram", "icon": "✈️", "code": "tg", "fivesim_code": "telegram", "short": "Telegram"},
    "ig": {"id": "instagram", "name": "إنستغرام Instagram", "icon": "📸", "code": "ig", "fivesim_code": "instagram", "short": "Instagram"},
    "fb": {"id": "facebook", "name": "فيسبوك Facebook", "icon": "👤", "code": "fb", "fivesim_code": "facebook", "short": "Facebook"},
    "tw": {"id": "twitter", "name": "تويتر / X", "icon": "🐦", "code": "tw", "fivesim_code": "twitter", "short": "Twitter (X)"},
    "lf": {"id": "tiktok", "name": "تيك توك TikTok", "icon": "🎵", "code": "lf", "fivesim_code": "tiktok", "short": "TikTok"},
    "go": {"id": "google", "name": "جوجل Google / Gmail", "icon": "🔴", "code": "go", "fivesim_code": "google", "short": "Google"},
    "sn": {"id": "snapchat", "name": "سناب شات Snapchat", "icon": "👻", "code": "fu", "fivesim_code": "snapchat", "short": "Snapchat"},
    "hj": {"id": "haraj", "name": "حراج Haraj", "icon": "🏷️", "code": "au", "fivesim_code": "haraj", "short": "Haraj"},
    "im": {"id": "imo", "name": "إيمو IMO", "icon": "💬", "code": "im", "fivesim_code": "imo", "short": "IMO"},
    "pp": {"id": "paypal", "name": "بايبال PayPal", "icon": "🅿️", "code": "ts", "fivesim_code": "paypal", "short": "PayPal"},
    "vi": {"id": "viber", "name": "فايبر Viber", "icon": "📞", "code": "vi", "fivesim_code": "viber", "short": "Viber"},
    "ot": {"id": "other", "name": "أي تطبيق آخر", "icon": "📱", "code": "ot", "fivesim_code": "other", "short": "Any Other"}
}

# توفير MAIN_APPS بالمعرفات المباشرة للتوافق الكامل
MAIN_APPS = {
    "whatsapp": SERVICES["wa"],
    "telegram": SERVICES["tg"],
    "instagram": SERVICES["ig"],
    "facebook": SERVICES["fb"],
    "twitter": SERVICES["tw"],
    "tiktok": SERVICES["lf"],
    "google": SERVICES["go"],
    "snapchat": SERVICES["sn"],
    "haraj": SERVICES["hj"],
    "imo": SERVICES["im"],
    "paypal": SERVICES["pp"],
    "viber": SERVICES["vi"],
    "other": SERVICES["ot"]
}

# أقسام الرشق المعتمدة
SMM_SECTIONS = [
    {"id": "tg", "name": "خدمات تيليجرام ✈️", "title": "تيليجرام"},
    {"id": "ig", "name": "خدمات إنستغرام 📸", "title": "إنستغرام"},
    {"id": "tt", "name": "خدمات تيك توك 🎵", "title": "تيك توك"},
    {"id": "yt", "name": "خدمات يوتيوب 🔴", "title": "يوتيوب"},
    {"id": "tw", "name": "خدمات تويتر (X) 🐦", "title": "تويتر"},
    {"id": "fb", "name": "خدمات فيسبوك 👤", "title": "فيسبوك"},
    {"id": "wa", "name": "خدمات واتساب 💬", "title": "واتساب"},
    {"id": "games", "name": "شحن الألعاب والـ ID 🎮", "title": "ألعاب"},
]

# طرق الشحن المعتمدة للإدارة والمستخدمين
PAYMENT_METHODS = {
    "usdt": {
        "id": "usdt",
        "name": "USDT (TRC20)",
        "network": "TRON (TRC20)",
        "icon": "💵",
        "default_address": "TYDzsxdH7bF2jK49mQW8pE51vNxxxxxx",
        "desc": "إيداع رقمي فوري وآمن بدون عمولات إضافية.",
        "min": 1.0,
        "enabled": True
    },
    "payeer": {
        "id": "payeer",
        "name": "باير Payeer",
        "network": "Payeer USD",
        "icon": "🅿️",
        "default_address": "P1089234812",
        "desc": "إيداع فوري عبر بنك باير العالمي.",
        "min": 0.5,
        "enabled": True
    },
    "syriatel": {
        "id": "syriatel",
        "name": "سيرياتيل كاش (سوريا)",
        "network": "Syriatel Cash",
        "icon": "🇸🇾",
        "default_address": "0987654321",
        "desc": "تحويل فوري عبر كود سيرياتيل كاش بسعر الصرف اليومي.",
        "min": 0.5,
        "enabled": True
    },
    "yemen_mobile": {
        "id": "yemen_mobile",
        "name": "يمن موبايل / كريمي (اليمن)",
        "network": "Kuraimi / Yemen",
        "icon": "🇾🇪",
        "default_address": "حساب كريمي: 12345678 (باسم الإدارة)",
        "desc": "إيداع عبر بنك الكريمي أو محفظة جوالي ووان كاش.",
        "min": 0.5,
        "enabled": True
    },
    "vodafone": {
        "id": "vodafone",
        "name": "فودافون كاش / إنستاباي (مصر)",
        "network": "Vodafone Cash / InstaPay",
        "icon": "🇪🇬",
        "default_address": "01012345678 (فودافون كاش أو InstaPay)",
        "desc": "تحويل عبر محافظ مصر الإلكترونية بسعر السوق.",
        "min": 0.5,
        "enabled": True
    },
    "bankak": {
        "id": "bankak",
        "name": "بنكك (السودان)",
        "network": "Bank of Khartoum",
        "icon": "🇸🇩",
        "default_address": "حساب بنكك: 1829472",
        "desc": "تحويل عبر تطبيق بنك الخرطوم بنكك.",
        "min": 1.0,
        "enabled": True
    },
    "asia_hawala": {
        "id": "asia_hawala",
        "name": "آسيا حوالة / زين كاش (العراق)",
        "network": "Zain Cash / AsiaHawala",
        "icon": "🇮🇶",
        "default_address": "07801234567",
        "desc": "تحويل مباشر عبر محافظ العراق الرقمية.",
        "min": 1.0,
        "enabled": True
    }
}

# ==========================================
# السيرفرات المعتمدة (سيرفر 1: Hero SMS / سيرفر 2: 5SIM العالمي)
# ==========================================

SERVERS = {
    "s1": {
        "title": "⚡ السيرفر (1) Hero SMS",
        "provider": "hero",
        "badge": "HERO SMS"
    },
    "s2": {
        "title": "🌐 السيرفر (2) 5SIM العالمي",
        "provider": "fivesim",
        "badge": "5SIM"
    }
}

# ==========================================
# عروض أرقام وحسابات تيليجرام الجاهزة (موقع TG) لجميع دول العالم
# ==========================================
TG_READY_ACCOUNTS = {
    "tg_acc_ye": {"id": "tg_acc_ye", "code": "ye", "code_num": "967", "raw_name": "Yemen", "country": "🇾🇪 اليمن", "price_usd": 1.40, "price_rub": 42.0, "raw_price": 1.08, "qty": 15, "type": "Tdata + Session", "desc": "حساب يمني حقيقي ونادر مسجل وجاهز فورياً.", "search_kw": "اليمن yemen 967 ye"},
    "tg_acc_sa": {"id": "tg_acc_sa", "code": "sa", "code_num": "966", "raw_name": "Saudi Arabia", "country": "🇸🇦 السعودية", "price_usd": 1.60, "price_rub": 48.0, "raw_price": 1.23, "qty": 25, "type": "Tdata + Session", "desc": "حساب سعودي مميز (+966) مفعل وجاهز.", "search_kw": "السعودية saudi arabia 966 sa"},
    "tg_acc_eg": {"id": "tg_acc_eg", "code": "eg", "code_num": "20", "raw_name": "Egypt", "country": "🇪🇬 مصر", "price_usd": 0.65, "price_rub": 19.5, "raw_price": 0.50, "qty": 40, "type": "Session فوري", "desc": "حساب مصري نشط واقتصادي للرشق والتسويق.", "search_kw": "مصر egypt 20 eg"},
    "tg_acc_ae": {"id": "tg_acc_ae", "code": "ae", "code_num": "971", "raw_name": "UAE", "country": "🇦🇪 الإمارات", "price_usd": 1.80, "price_rub": 54.0, "raw_price": 1.38, "qty": 18, "type": "VIP Tdata", "desc": "حساب إماراتي رسمي (+971) عالي الأمان.", "search_kw": "الإمارات uae united arab emirates 971 ae"},
    "tg_acc_iq": {"id": "tg_acc_iq", "code": "iq", "code_num": "964", "raw_name": "Iraq", "country": "🇮🇶 العراق", "price_usd": 0.85, "price_rub": 25.5, "raw_price": 0.65, "qty": 30, "type": "Session فوري", "desc": "حساب عراقي سريع التحميل ومناسب لكل الأغراض.", "search_kw": "العراق iraq 964 iq"},
    "tg_acc_ma": {"id": "tg_acc_ma", "code": "ma", "code_num": "212", "raw_name": "Morocco", "country": "🇲🇦 المغرب", "price_usd": 0.70, "price_rub": 21.0, "raw_price": 0.54, "qty": 22, "type": "Tdata + Session", "desc": "حساب مغربي موثق وثابت جداً.", "search_kw": "المغرب morocco 212 ma"},
    "tg_acc_dz": {"id": "tg_acc_dz", "code": "dz", "code_num": "213", "raw_name": "Algeria", "country": "🇩🇿 الجزائر", "price_usd": 0.70, "price_rub": 21.0, "raw_price": 0.54, "qty": 20, "type": "Session فوري", "desc": "حساب جزائري جاهز للتسليم الآلي.", "search_kw": "الجزائر algeria 213 dz"},
    "tg_acc_tn": {"id": "tg_acc_tn", "code": "tn", "code_num": "216", "raw_name": "Tunisia", "country": "🇹🇳 تونس", "price_usd": 0.75, "price_rub": 22.5, "raw_price": 0.58, "qty": 15, "type": "Session فوري", "desc": "حساب تونسي مفعل وجاهز.", "search_kw": "تونس tunisia 216 tn"},
    "tg_acc_ly": {"id": "tg_acc_ly", "code": "ly", "code_num": "218", "raw_name": "Libya", "country": "🇱🇾 ليبيا", "price_usd": 0.90, "price_rub": 27.0, "raw_price": 0.69, "qty": 14, "type": "Tdata جاهز", "desc": "حساب ليبي رسمي ممتاز.", "search_kw": "ليبيا libya 218 ly"},
    "tg_acc_sd": {"id": "tg_acc_sd", "code": "sd", "code_num": "249", "raw_name": "Sudan", "country": "🇸🇩 السودان", "price_usd": 0.80, "price_rub": 24.0, "raw_price": 0.62, "qty": 12, "type": "Session فوري", "desc": "حساب سوداني نشط وثابت.", "search_kw": "السودان sudan 249 sd"},
    "tg_acc_sy": {"id": "tg_acc_sy", "code": "sy", "code_num": "963", "raw_name": "Syria", "country": "🇸🇾 سوريا", "price_usd": 1.10, "price_rub": 33.0, "raw_price": 0.85, "qty": 10, "type": "Tdata + Session", "desc": "حساب سوري موثق.", "search_kw": "سوريا syria 963 sy"},
    "tg_acc_jo": {"id": "tg_acc_jo", "code": "jo", "code_num": "962", "raw_name": "Jordan", "country": "🇯🇴 الأردن", "price_usd": 1.00, "price_rub": 30.0, "raw_price": 0.77, "qty": 16, "type": "Tdata + Session", "desc": "حساب أردني (+962) جاهز.", "search_kw": "الأردن jordan 962 jo"},
    "tg_acc_ps": {"id": "tg_acc_ps", "code": "ps", "code_num": "970", "raw_name": "Palestine", "country": "🇵🇸 فلسطين", "price_usd": 1.20, "price_rub": 36.0, "raw_price": 0.92, "qty": 10, "type": "VIP Session", "desc": "حساب فلسطيني أصلي.", "search_kw": "فلسطين palestine 970 ps"},
    "tg_acc_lb": {"id": "tg_acc_lb", "code": "lb", "code_num": "961", "raw_name": "Lebanon", "country": "🇱🇧 لبنان", "price_usd": 0.95, "price_rub": 28.5, "raw_price": 0.73, "qty": 12, "type": "Session فوري", "desc": "حساب لبناني مفعل.", "search_kw": "لبنان lebanon 961 lb"},
    "tg_acc_kw": {"id": "tg_acc_kw", "code": "kw", "code_num": "965", "raw_name": "Kuwait", "country": "🇰🇼 الكويت", "price_usd": 1.70, "price_rub": 51.0, "raw_price": 1.30, "qty": 15, "type": "Tdata VIP", "desc": "حساب كويتي (+965) مميز.", "search_kw": "الكويت kuwait 965 kw"},
    "tg_acc_qa": {"id": "tg_acc_qa", "code": "qa", "code_num": "974", "raw_name": "Qatar", "country": "🇶🇦 قطر", "price_usd": 1.80, "price_rub": 54.0, "raw_price": 1.38, "qty": 14, "type": "Tdata VIP", "desc": "حساب قطري رسمي.", "search_kw": "قطر qatar 974 qa"},
    "tg_acc_om": {"id": "tg_acc_om", "code": "om", "code_num": "968", "raw_name": "Oman", "country": "🇴🇲 سلطنة عمان", "price_usd": 1.50, "price_rub": 45.0, "raw_price": 1.15, "qty": 16, "type": "Tdata + Session", "desc": "حساب عماني مفعل.", "search_kw": "عمان oman 968 om"},
    "tg_acc_bh": {"id": "tg_acc_bh", "code": "bh", "code_num": "973", "raw_name": "Bahrain", "country": "🇧🇭 البحرين", "price_usd": 1.60, "price_rub": 48.0, "raw_price": 1.23, "qty": 12, "type": "Tdata VIP", "desc": "حساب بحريني جاهز.", "search_kw": "البحرين bahrain 973 bh"},
    "tg_acc_usa": {"id": "tg_acc_usa", "code": "us", "code_num": "1", "raw_name": "USA", "country": "🇺🇸 أمريكا", "price_usd": 0.45, "price_rub": 13.5, "raw_price": 0.35, "qty": 85, "type": "Tdata / Session", "desc": "حساب أمريكي سريع واقتصادي جداً.", "search_kw": "أمريكا usa united states 1 us"},
    "tg_acc_ru": {"id": "tg_acc_ru", "code": "ru", "code_num": "7", "raw_name": "Russia", "country": "🇷🇺 روسيا", "price_usd": 0.35, "price_rub": 10.5, "raw_price": 0.27, "qty": 90, "type": "Session عالي الثبات", "desc": "الحساب الأكثر استقراراً ومناسب للبوتات والقنوات.", "search_kw": "روسيا russia 7 ru"},
    "tg_acc_uk": {"id": "tg_acc_uk", "code": "gb", "code_num": "44", "raw_name": "United Kingdom", "country": "🇬🇧 بريطانيا", "price_usd": 1.10, "price_rub": 33.0, "raw_price": 0.85, "qty": 20, "type": "Tdata + Session", "desc": "حساب بريطاني مميز (+44).", "search_kw": "بريطانيا uk britain england 44 gb"},
    "tg_acc_id": {"id": "tg_acc_id", "code": "id", "code_num": "62", "raw_name": "Indonesia", "country": "🇮🇩 إندونيسيا", "price_usd": 0.25, "price_rub": 7.5, "raw_price": 0.19, "qty": 110, "type": "Session اقتصادي", "desc": "أرخص حسابات الرشق والتسويق الضخم.", "search_kw": "إندونيسيا indonesia 62 id"},
    "tg_acc_br": {"id": "tg_acc_br", "code": "br", "code_num": "55", "raw_name": "Brazil", "country": "🇧🇷 البرازيل", "price_usd": 0.40, "price_rub": 12.0, "raw_price": 0.31, "qty": 65, "type": "Session فوري", "desc": "حساب برازيلي ممتاز للرشق والتفاعل.", "search_kw": "البرازيل brazil 55 br"},
    "tg_acc_tr": {"id": "tg_acc_tr", "code": "tr", "code_num": "90", "raw_name": "Turkey", "country": "🇹🇷 تركيا", "price_usd": 0.60, "price_rub": 18.0, "raw_price": 0.46, "qty": 35, "type": "Tdata + Session", "desc": "حساب تركي مفعل.", "search_kw": "تركيا turkey 90 tr"},
    "tg_acc_in": {"id": "tg_acc_in", "code": "in", "code_num": "91", "raw_name": "India", "country": "🇮🇳 الهند", "price_usd": 0.30, "price_rub": 9.0, "raw_price": 0.23, "qty": 120, "type": "Session فوري", "desc": "حساب هندي رخيص ومتاح بكميات هائلة.", "search_kw": "الهند india 91 in"},
    "tg_acc_pk": {"id": "tg_acc_pk", "code": "pk", "code_num": "92", "raw_name": "Pakistan", "country": "🇵🇰 باكستان", "price_usd": 0.35, "price_rub": 10.5, "raw_price": 0.27, "qty": 70, "type": "Session فوري", "desc": "حساب باكستاني جاهز للعمل.", "search_kw": "باكستان pakistan 92 pk"},
    "tg_acc_de": {"id": "tg_acc_de", "code": "de", "code_num": "49", "raw_name": "Germany", "country": "🇩🇪 ألمانيا", "price_usd": 1.50, "price_rub": 45.0, "raw_price": 1.15, "qty": 18, "type": "Tdata VIP", "desc": "حساب ألماني موثوق (+49).", "search_kw": "ألمانيا germany 49 de"},
    "tg_acc_fr": {"id": "tg_acc_fr", "code": "fr", "code_num": "33", "raw_name": "France", "country": "🇫🇷 فرنسا", "price_usd": 1.50, "price_rub": 45.0, "raw_price": 1.15, "qty": 16, "type": "Tdata VIP", "desc": "حساب فرنسي رسمي (+33).", "search_kw": "فرنسا france 33 fr"},
    "tg_acc_es": {"id": "tg_acc_es", "code": "es", "code_num": "34", "raw_name": "Spain", "country": "🇪🇸 إسبانيا", "price_usd": 1.20, "price_rub": 36.0, "raw_price": 0.92, "qty": 14, "type": "Tdata + Session", "desc": "حساب إسباني موثق.", "search_kw": "إسبانيا spain 34 es"},
    "tg_acc_it": {"id": "tg_acc_it", "code": "it", "code_num": "39", "raw_name": "Italy", "country": "🇮🇹 إيطاليا", "price_usd": 1.30, "price_rub": 39.0, "raw_price": 1.00, "qty": 15, "type": "Tdata + Session", "desc": "حساب إيطالي مفعل.", "search_kw": "إيطاليا italy 39 it"},
    "tg_acc_ca": {"id": "tg_acc_ca", "code": "ca", "code_num": "1", "raw_name": "Canada", "country": "🇨🇦 كندا", "price_usd": 0.80, "price_rub": 24.0, "raw_price": 0.62, "qty": 30, "type": "Tdata / Session", "desc": "حساب كندي نشط (+1).", "search_kw": "كندا canada 1 ca"},
    "tg_acc_vn": {"id": "tg_acc_vn", "code": "vn", "code_num": "84", "raw_name": "Vietnam", "country": "🇻🇳 فيتنام", "price_usd": 0.30, "price_rub": 9.0, "raw_price": 0.23, "qty": 80, "type": "Session اقتصادي", "desc": "حساب فيتنامي مثالي للرشق.", "search_kw": "فيتنام vietnam 84 vn"},
    "tg_acc_my": {"id": "tg_acc_my", "code": "my", "code_num": "60", "raw_name": "Malaysia", "country": "🇲🇾 ماليزيا", "price_usd": 0.50, "price_rub": 15.0, "raw_price": 0.38, "qty": 35, "type": "Session فوري", "desc": "حساب ماليزي نشط.", "search_kw": "ماليزيا malaysia 60 my"},
    "tg_acc_ph": {"id": "tg_acc_ph", "code": "ph", "code_num": "63", "raw_name": "Philippines", "country": "🇵🇭 الفلبين", "price_usd": 0.40, "price_rub": 12.0, "raw_price": 0.31, "qty": 45, "type": "Session فوري", "desc": "حساب فلبيني سريع.", "search_kw": "الفلبين philippines 63 ph"},
    "tg_acc_kz": {"id": "tg_acc_kz", "code": "kz", "code_num": "7", "raw_name": "Kazakhstan", "country": "🇰🇿 كازاخستان", "price_usd": 0.55, "price_rub": 16.5, "raw_price": 0.42, "qty": 40, "type": "Tdata + Session", "desc": "حساب كازاخستاني عالي الجودة.", "search_kw": "كازاخستان kazakhstan 7 kz"},
    "tg_acc_uz": {"id": "tg_acc_uz", "code": "uz", "code_num": "998", "raw_name": "Uzbekistan", "country": "🇺🇿 أوزبكستان", "price_usd": 0.55, "price_rub": 16.5, "raw_price": 0.42, "qty": 35, "type": "Session فوري", "desc": "حساب أوزبكي ممتاز.", "search_kw": "أوزبكستان uzbekistan 998 uz"},
    "tg_acc_ng": {"id": "tg_acc_ng", "code": "ng", "code_num": "234", "raw_name": "Nigeria", "country": "🇳🇬 نيجيريا", "price_usd": 0.30, "price_rub": 9.0, "raw_price": 0.23, "qty": 100, "type": "Session اقتصادي", "desc": "حساب نيجيري فائق السرعة.", "search_kw": "نيجيريا nigeria 234 ng"},
    "tg_acc_za": {"id": "tg_acc_za", "code": "za", "code_num": "27", "raw_name": "South Africa", "country": "🇿🇦 جنوب إفريقيا", "price_usd": 0.65, "price_rub": 19.5, "raw_price": 0.50, "qty": 25, "type": "Session فوري", "desc": "حساب جنوب إفريقي جاهز.", "search_kw": "جنوب إفريقيا south africa 27 za"},
    "tg_acc_co": {"id": "tg_acc_co", "code": "co", "code_num": "57", "raw_name": "Colombia", "country": "🇨🇴 كولومبيا", "price_usd": 0.45, "price_rub": 13.5, "raw_price": 0.35, "qty": 30, "type": "Session فوري", "desc": "حساب كولومبي نشط.", "search_kw": "كولومبيا colombia 57 co"},
    "tg_acc_ar": {"id": "tg_acc_ar", "code": "ar", "code_num": "54", "raw_name": "Argentina", "country": "🇦🇷 الأرجنتين", "price_usd": 0.50, "price_rub": 15.0, "raw_price": 0.38, "qty": 28, "type": "Session فوري", "desc": "حساب أرجنتيني متاح فورياً.", "search_kw": "الأرجنتين argentina 54 ar"},
    "tg_acc_mx": {"id": "tg_acc_mx", "code": "mx", "code_num": "52", "raw_name": "Mexico", "country": "🇲🇽 المكسيك", "price_usd": 0.60, "price_rub": 18.0, "raw_price": 0.46, "qty": 32, "type": "Session فوري", "desc": "حساب مكسيكي نشط.", "search_kw": "المكسيك mexico 52 mx"},
    "tg_acc_pl": {"id": "tg_acc_pl", "code": "pl", "code_num": "48", "raw_name": "Poland", "country": "🇵🇱 بولندا", "price_usd": 0.90, "price_rub": 27.0, "raw_price": 0.69, "qty": 20, "type": "Tdata + Session", "desc": "حساب بولندي أوروبي.", "search_kw": "بولندا poland 48 pl"},
    "tg_acc_nl": {"id": "tg_acc_nl", "code": "nl", "code_num": "31", "raw_name": "Netherlands", "country": "🇳🇱 هولندا", "price_usd": 1.40, "price_rub": 42.0, "raw_price": 1.08, "qty": 15, "type": "Tdata VIP", "desc": "حساب هولندي عالي الأمان.", "search_kw": "هولندا netherlands 31 nl"},
    "tg_acc_se": {"id": "tg_acc_se", "code": "se", "code_num": "46", "raw_name": "Sweden", "country": "🇸🇪 السويد", "price_usd": 1.40, "price_rub": 42.0, "raw_price": 1.08, "qty": 14, "type": "Tdata VIP", "desc": "حساب سويدي (+46).", "search_kw": "السويد sweden 46 se"},
    "tg_acc_ua": {"id": "tg_acc_ua", "code": "ua", "code_num": "380", "raw_name": "Ukraine", "country": "🇺🇦 أوكرانيا", "price_usd": 0.50, "price_rub": 15.0, "raw_price": 0.38, "qty": 35, "type": "Session فوري", "desc": "حساب أوكراني نشط.", "search_kw": "أوكرانيا ukraine 380 ua"}
}

# خريطة الترجمة الشاملة لأسماء الدول وكود الآيزو ISO-2 لجميع دول العالم
GLOBAL_COUNTRY_TRANSLATIONS = {
    "ye": {"title": "اليمن", "flag": "🇾🇪", "id": "54", "prefix": "967"},
    "yemen": {"title": "اليمن", "flag": "🇾🇪", "id": "54", "prefix": "967"},
    "sa": {"title": "السعودية", "flag": "🇸🇦", "id": "53", "prefix": "966"},
    "saudi": {"title": "السعودية", "flag": "🇸🇦", "id": "53", "prefix": "966"},
    "saudiarabia": {"title": "السعودية", "flag": "🇸🇦", "id": "53", "prefix": "966"},
    "eg": {"title": "مصر", "flag": "🇪🇬", "id": "21", "prefix": "20"},
    "egypt": {"title": "مصر", "flag": "🇪🇬", "id": "21", "prefix": "20"},
    "ae": {"title": "الإمارات", "flag": "🇦🇪", "id": "95", "prefix": "971"},
    "uae": {"title": "الإمارات", "flag": "🇦🇪", "id": "95", "prefix": "971"},
    "unitedarabemirates": {"title": "الإمارات", "flag": "🇦🇪", "id": "95", "prefix": "971"},
    "iq": {"title": "العراق", "flag": "🇮🇶", "id": "52", "prefix": "964"},
    "iraq": {"title": "العراق", "flag": "🇮🇶", "id": "52", "prefix": "964"},
    "sy": {"title": "سوريا", "flag": "🇸🇾", "id": "110", "prefix": "963"},
    "syria": {"title": "سوريا", "flag": "🇸🇾", "id": "110", "prefix": "963"},
    "jo": {"title": "الأردن", "flag": "🇯🇴", "id": "116", "prefix": "962"},
    "jordan": {"title": "الأردن", "flag": "🇯🇴", "id": "116", "prefix": "962"},
    "kw": {"title": "الكويت", "flag": "🇰🇼", "id": "117", "prefix": "965"},
    "kuwait": {"title": "الكويت", "flag": "🇰🇼", "id": "117", "prefix": "965"},
    "om": {"title": "عمان", "flag": "🇴🇲", "id": "148", "prefix": "968"},
    "oman": {"title": "عمان", "flag": "🇴🇲", "id": "148", "prefix": "968"},
    "qa": {"title": "قطر", "flag": "🇶🇦", "id": "111", "prefix": "974"},
    "qatar": {"title": "قطر", "flag": "🇶🇦", "id": "111", "prefix": "974"},
    "bh": {"title": "البحرين", "flag": "🇧🇭", "id": "145", "prefix": "973"},
    "bahrain": {"title": "البحرين", "flag": "🇧🇭", "id": "145", "prefix": "973"},
    "lb": {"title": "لبنان", "flag": "🇱🇧", "id": "107", "prefix": "961"},
    "lebanon": {"title": "لبنان", "flag": "🇱🇧", "id": "107", "prefix": "961"},
    "ps": {"title": "فلسطين", "flag": "🇵🇸", "id": "146", "prefix": "970"},
    "palestine": {"title": "فلسطين", "flag": "🇵🇸", "id": "146", "prefix": "970"},
    "il": {"title": "فلسطين", "flag": "🇵🇸", "id": "146", "prefix": "970"},
    "sd": {"title": "السودان", "flag": "🇸🇩", "id": "114", "prefix": "249"},
    "sudan": {"title": "السودان", "flag": "🇸🇩", "id": "114", "prefix": "249"},
    "ly": {"title": "ليبيا", "flag": "🇱🇾", "id": "108", "prefix": "218"},
    "libya": {"title": "ليبيا", "flag": "🇱🇾", "id": "108", "prefix": "218"},
    "dz": {"title": "الجزائر", "flag": "🇩🇿", "id": "58", "prefix": "213"},
    "algeria": {"title": "الجزائر", "flag": "🇩🇿", "id": "58", "prefix": "213"},
    "ma": {"title": "المغرب", "flag": "🇲🇦", "id": "102", "prefix": "212"},
    "morocco": {"title": "المغرب", "flag": "🇲🇦", "id": "102", "prefix": "212"},
    "tn": {"title": "تونس", "flag": "🇹🇳", "id": "89", "prefix": "216"},
    "tunisia": {"title": "تونس", "flag": "🇹🇳", "id": "89", "prefix": "216"},
    "mr": {"title": "موريتانيا", "flag": "🇲🇷", "id": "195", "prefix": "222"},
    "mauritania": {"title": "موريتانيا", "flag": "🇲🇷", "id": "195", "prefix": "222"},
    "so": {"title": "الصومال", "flag": "🇸🇴", "id": "149", "prefix": "252"},
    "somalia": {"title": "الصومال", "flag": "🇸🇴", "id": "149", "prefix": "252"},
    "dj": {"title": "جيبوتي", "flag": "🇩🇯", "id": "168", "prefix": "253"},
    "djibouti": {"title": "جيبوتي", "flag": "🇩🇯", "id": "168", "prefix": "253"},
    "km": {"title": "جزر القمر", "flag": "🇰🇲", "id": "133", "prefix": "269"},
    "comoros": {"title": "جزر القمر", "flag": "🇰🇲", "id": "133", "prefix": "269"},
    "us": {"title": "أمريكا", "flag": "🇺🇸", "id": "187", "prefix": "1"},
    "usa": {"title": "أمريكا", "flag": "🇺🇸", "id": "187", "prefix": "1"},
    "unitedstates": {"title": "أمريكا", "flag": "🇺🇸", "id": "187", "prefix": "1"},
    "ru": {"title": "روسيا", "flag": "🇷🇺", "id": "0", "prefix": "7"},
    "russia": {"title": "روسيا", "flag": "🇷🇺", "id": "0", "prefix": "7"},
    "gb": {"title": "بريطانيا", "flag": "🇬🇧", "id": "16", "prefix": "44"},
    "uk": {"title": "بريطانيا", "flag": "🇬🇧", "id": "16", "prefix": "44"},
    "unitedkingdom": {"title": "بريطانيا", "flag": "🇬🇧", "id": "16", "prefix": "44"},
    "england": {"title": "بريطانيا", "flag": "🇬🇧", "id": "16", "prefix": "44"},
    "de": {"title": "ألمانيا", "flag": "🇩🇪", "id": "13", "prefix": "49"},
    "germany": {"title": "ألمانيا", "flag": "🇩🇪", "id": "13", "prefix": "49"},
    "fr": {"title": "فرنسا", "flag": "🇫🇷", "id": "78", "prefix": "33"},
    "france": {"title": "فرنسا", "flag": "🇫🇷", "id": "78", "prefix": "33"},
    "tr": {"title": "تركيا", "flag": "🇹🇷", "id": "60", "prefix": "90"},
    "turkey": {"title": "تركيا", "flag": "🇹🇷", "id": "60", "prefix": "90"},
    "uz": {"title": "أوزبكستان", "flag": "🇺🇿", "id": "19", "prefix": "998"},
    "uzbekistan": {"title": "أوزبكستان", "flag": "🇺🇿", "id": "19", "prefix": "998"},
    "bd": {"title": "بنغلاديش", "flag": "🇧🇩", "id": "40", "prefix": "880"},
    "bangladesh": {"title": "بنغلاديش", "flag": "🇧🇩", "id": "40", "prefix": "880"},
    "kz": {"title": "كازاخستان", "flag": "🇰🇿", "id": "2", "prefix": "77"},
    "kazakhstan": {"title": "كازاخستان", "flag": "🇰🇿", "id": "2", "prefix": "77"},
    "kg": {"title": "قيرغيزستان", "flag": "🇰🇬", "id": "11", "prefix": "996"},
    "kyrgyzstan": {"title": "قيرغيزستان", "flag": "🇰🇬", "id": "11", "prefix": "996"},
    "tj": {"title": "طاجيكستان", "flag": "🇹🇯", "id": "143", "prefix": "992"},
    "tajikistan": {"title": "طاجيكستان", "flag": "🇹🇯", "id": "143", "prefix": "992"},
    "tm": {"title": "تركمانستان", "flag": "🇹🇲", "id": "161", "prefix": "993"},
    "turkmenistan": {"title": "تركمانستان", "flag": "🇹🇲", "id": "161", "prefix": "993"},
    "az": {"title": "أذربيجان", "flag": "🇦🇿", "id": "35", "prefix": "994"},
    "azerbaijan": {"title": "أذربيجان", "flag": "🇦🇿", "id": "35", "prefix": "994"},
    "am": {"title": "أرمينيا", "flag": "🇦🇲", "id": "148", "prefix": "374"},
    "armenia": {"title": "أرمينيا", "flag": "🇦🇲", "id": "148", "prefix": "374"},
    "ge": {"title": "جورجيا", "flag": "🇬🇪", "id": "94", "prefix": "995"},
    "georgia": {"title": "جورجيا", "flag": "🇬🇪", "id": "94", "prefix": "995"},
    "ua": {"title": "أوكرانيا", "flag": "🇺🇦", "id": "1", "prefix": "380"},
    "ukraine": {"title": "أوكرانيا", "flag": "🇺🇦", "id": "1", "prefix": "380"},
    "id": {"title": "إندونيسيا", "flag": "🇮🇩", "id": "6", "prefix": "62"},
    "indonesia": {"title": "إندونيسيا", "flag": "🇮🇩", "id": "6", "prefix": "62"},
    "my": {"title": "ماليزيا", "flag": "🇲🇾", "id": "7", "prefix": "60"},
    "malaysia": {"title": "ماليزيا", "flag": "🇲🇾", "id": "7", "prefix": "60"},
    "ph": {"title": "الفلبين", "flag": "🇵🇭", "id": "4", "prefix": "63"},
    "philippines": {"title": "الفلبين", "flag": "🇵🇭", "id": "4", "prefix": "63"},
    "vn": {"title": "فيتنام", "flag": "🇻🇳", "id": "10", "prefix": "84"},
    "vietnam": {"title": "فيتنام", "flag": "🇻🇳", "id": "10", "prefix": "84"},
    "th": {"title": "تايلاند", "flag": "🇹🇭", "id": "51", "prefix": "66"},
    "thailand": {"title": "تايلاند", "flag": "🇹🇭", "id": "51", "prefix": "66"},
    "in": {"title": "الهند", "flag": "🇮🇳", "id": "22", "prefix": "91"},
    "india": {"title": "الهند", "flag": "🇮🇳", "id": "22", "prefix": "91"},
    "pk": {"title": "باكستان", "flag": "🇵🇰", "id": "38", "prefix": "92"},
    "pakistan": {"title": "باكستان", "flag": "🇵🇰", "id": "38", "prefix": "92"},
    "af": {"title": "أفغانستان", "flag": "🇦🇫", "id": "115", "prefix": "93"},
    "afghanistan": {"title": "أفغانستان", "flag": "🇦🇫", "id": "115", "prefix": "93"},
    "mx": {"title": "المكسيك", "flag": "🇲🇽", "id": "54", "prefix": "52"},
    "mexico": {"title": "المكسيك", "flag": "🇲🇽", "id": "54", "prefix": "52"},
    "br": {"title": "البرازيل", "flag": "🇧🇷", "id": "73", "prefix": "55"},
    "brazil": {"title": "البرازيل", "flag": "🇧🇷", "id": "73", "prefix": "55"},
    "co": {"title": "كولومبيا", "flag": "🇨🇴", "id": "33", "prefix": "57"},
    "colombia": {"title": "كولومبيا", "flag": "🇨🇴", "id": "33", "prefix": "57"},
    "ar": {"title": "الأرجنتين", "flag": "🇦🇷", "id": "67", "prefix": "54"},
    "argentina": {"title": "الأرجنتين", "flag": "🇦🇷", "id": "67", "prefix": "54"},
    "cl": {"title": "تشيلي", "flag": "🇨🇱", "id": "87", "prefix": "56"},
    "chile": {"title": "تشيلي", "flag": "🇨🇱", "id": "87", "prefix": "56"},
    "pe": {"title": "بيرو", "flag": "🇵🇪", "id": "62", "prefix": "51"},
    "peru": {"title": "بيرو", "flag": "🇵🇪", "id": "62", "prefix": "51"},
    "ec": {"title": "الإكوادور", "flag": "🇪🇨", "id": "105", "prefix": "593"},
    "ecuador": {"title": "الإكوادور", "flag": "🇪🇨", "id": "105", "prefix": "593"},
    "ve": {"title": "فنزويلا", "flag": "🇻🇪", "id": "70", "prefix": "58"},
    "venezuela": {"title": "فنزويلا", "flag": "🇻🇪", "id": "70", "prefix": "58"},
    "uy": {"title": "الأوروغواي", "flag": "🇺🇾", "id": "156", "prefix": "598"},
    "uruguay": {"title": "الأوروغواي", "flag": "🇺🇾", "id": "156", "prefix": "598"},
    "ca": {"title": "كندا", "flag": "🇨🇦", "id": "36", "prefix": "1"},
    "canada": {"title": "كندا", "flag": "🇨🇦", "id": "36", "prefix": "1"},
    "es": {"title": "إسبانيا", "flag": "🇪🇸", "id": "56", "prefix": "34"},
    "spain": {"title": "إسبانيا", "flag": "🇪🇸", "id": "56", "prefix": "34"},
    "it": {"title": "إيطاليا", "flag": "🇮🇹", "id": "86", "prefix": "39"},
    "italy": {"title": "إيطاليا", "flag": "🇮🇹", "id": "86", "prefix": "39"},
    "pt": {"title": "البرتغال", "flag": "🇵🇹", "id": "117", "prefix": "351"},
    "portugal": {"title": "البرتغال", "flag": "🇵🇹", "id": "117", "prefix": "351"},
    "nl": {"title": "هولندا", "flag": "🇳🇱", "id": "48", "prefix": "31"},
    "netherlands": {"title": "هولندا", "flag": "🇳🇱", "id": "48", "prefix": "31"},
    "be": {"title": "بلجيكا", "flag": "🇧🇪", "id": "82", "prefix": "32"},
    "belgium": {"title": "بلجيكا", "flag": "🇧🇪", "id": "82", "prefix": "32"},
    "pl": {"title": "بولندا", "flag": "🇵🇱", "id": "15", "prefix": "48"},
    "poland": {"title": "بولندا", "flag": "🇵🇱", "id": "15", "prefix": "48"},
    "se": {"title": "السويد", "flag": "🇸🇪", "id": "46", "prefix": "46"},
    "sweden": {"title": "السويد", "flag": "🇸🇪", "id": "46", "prefix": "46"},
    "no": {"title": "النرويج", "flag": "🇳🇴", "id": "172", "prefix": "47"},
    "norway": {"title": "النرويج", "flag": "🇳🇴", "id": "172", "prefix": "47"},
    "dk": {"title": "الدنمارك", "flag": "🇩🇰", "id": "171", "prefix": "45"},
    "denmark": {"title": "الدنمارك", "flag": "🇩🇰", "id": "171", "prefix": "45"},
    "fi": {"title": "فنلندا", "flag": "🇫🇮", "id": "170", "prefix": "358"},
    "finland": {"title": "فنلندا", "flag": "🇫🇮", "id": "170", "prefix": "358"},
    "ch": {"title": "سويسرا", "flag": "🇨🇭", "id": "80", "prefix": "41"},
    "switzerland": {"title": "سويسرا", "flag": "🇨🇭", "id": "80", "prefix": "41"},
    "at": {"title": "النمسا", "flag": "🇦🇹", "id": "77", "prefix": "43"},
    "austria": {"title": "النمسا", "flag": "🇦🇹", "id": "77", "prefix": "43"},
    "cz": {"title": "التشيك", "flag": "🇨🇿", "id": "43", "prefix": "420"},
    "czech": {"title": "التشيك", "flag": "🇨🇿", "id": "43", "prefix": "420"},
    "ro": {"title": "رومانيا", "flag": "🇷🇴", "id": "32", "prefix": "40"},
    "romania": {"title": "رومانيا", "flag": "🇷🇴", "id": "32", "prefix": "40"},
    "gr": {"title": "اليونان", "flag": "🇬🇷", "id": "100", "prefix": "30"},
    "greece": {"title": "اليونان", "flag": "🇬🇷", "id": "100", "prefix": "30"},
    "hu": {"title": "المجر", "flag": "🇭🇺", "id": "84", "prefix": "36"},
    "hungary": {"title": "المجر", "flag": "🇭🇺", "id": "84", "prefix": "36"},
    "bg": {"title": "بلغاريا", "flag": "🇧🇬", "id": "83", "prefix": "359"},
    "bulgaria": {"title": "بلغاريا", "flag": "🇧🇬", "id": "83", "prefix": "359"},
    "al": {"title": "ألبانيا", "flag": "🇦🇱", "id": "155", "prefix": "355"},
    "albania": {"title": "ألبانيا", "flag": "🇦🇱", "id": "155", "prefix": "355"},
    "hr": {"title": "كرواتيا", "flag": "🇭🇷", "id": "45", "prefix": "385"},
    "croatia": {"title": "كرواتيا", "flag": "🇭🇷", "id": "45", "prefix": "385"},
    "rs": {"title": "صربيا", "flag": "🇷🇸", "id": "29", "prefix": "381"},
    "serbia": {"title": "صربيا", "flag": "🇷🇸", "id": "29", "prefix": "381"},
    "ba": {"title": "البوسنة والهرسك", "flag": "🇧🇦", "id": "165", "prefix": "387"},
    "bosnia": {"title": "البوسنة والهرسك", "flag": "🇧🇦", "id": "165", "prefix": "387"},
    "ie": {"title": "أيرلندا", "flag": "🇮🇪", "id": "23", "prefix": "353"},
    "ireland": {"title": "أيرلندا", "flag": "🇮🇪", "id": "23", "prefix": "353"},
    "is": {"title": "آيسلندا", "flag": "🇮🇸", "id": "132", "prefix": "354"},
    "iceland": {"title": "آيسلندا", "flag": "🇮🇸", "id": "132", "prefix": "354"},
    "lt": {"title": "ليتوانيا", "flag": "🇱🇹", "id": "13", "prefix": "370"},
    "lithuania": {"title": "ليتوانيا", "flag": "🇱🇹", "id": "13", "prefix": "370"},
    "lv": {"title": "لاتفيا", "flag": "🇱🇻", "id": "49", "prefix": "371"},
    "latvia": {"title": "لاتفيا", "flag": "🇱🇻", "id": "49", "prefix": "371"},
    "ee": {"title": "إستونيا", "flag": "🇪🇪", "id": "34", "prefix": "372"},
    "estonia": {"title": "إستونيا", "flag": "🇪🇪", "id": "34", "prefix": "372"},
    "cy": {"title": "قبرص", "flag": "🇨🇾", "id": "77", "prefix": "357"},
    "cyprus": {"title": "قبرص", "flag": "🇨🇾", "id": "77", "prefix": "357"},
    "mt": {"title": "مالطا", "flag": "🇲🇹", "id": "199", "prefix": "356"},
    "malta": {"title": "مالطا", "flag": "🇲🇹", "id": "199", "prefix": "356"},
    "md": {"title": "مولدوفا", "flag": "🇲🇩", "id": "37", "prefix": "373"},
    "moldova": {"title": "مولدوفا", "flag": "🇲🇩", "id": "37", "prefix": "373"},
    "by": {"title": "بيلاروسيا", "flag": "🇧🇾", "id": "51", "prefix": "375"},
    "belarus": {"title": "بيلاروسيا", "flag": "🇧🇾", "id": "51", "prefix": "375"},
    "au": {"title": "أستراليا", "flag": "🇦🇺", "id": "167", "prefix": "61"},
    "australia": {"title": "أستراليا", "flag": "🇦🇺", "id": "167", "prefix": "61"},
    "nz": {"title": "نيوزيلندا", "flag": "🇳🇿", "id": "67", "prefix": "64"},
    "newzealand": {"title": "نيوزيلندا", "flag": "🇳🇿", "id": "67", "prefix": "64"},
    "jp": {"title": "اليابان", "flag": "🇯🇵", "id": "182", "prefix": "81"},
    "japan": {"title": "اليابان", "flag": "🇯🇵", "id": "182", "prefix": "81"},
    "kr": {"title": "كوريا الجنوبية", "flag": "🇰🇷", "id": "190", "prefix": "82"},
    "korea": {"title": "كوريا الجنوبية", "flag": "🇰🇷", "id": "190", "prefix": "82"},
    "cn": {"title": "الصين", "flag": "🇨🇳", "id": "3", "prefix": "86"},
    "china": {"title": "الصين", "flag": "🇨🇳", "id": "3", "prefix": "86"},
    "hk": {"title": "هونغ كونغ", "flag": "🇭🇰", "id": "14", "prefix": "852"},
    "hongkong": {"title": "هونغ كونغ", "flag": "🇭🇰", "id": "14", "prefix": "852"},
    "tw": {"title": "تايوان", "flag": "🇹🇼", "id": "57", "prefix": "886"},
    "taiwan": {"title": "تايوان", "flag": "🇹🇼", "id": "57", "prefix": "886"},
    "sg": {"title": "سنغافورة", "flag": "🇸🇬", "id": "192", "prefix": "65"},
    "singapore": {"title": "سنغافورة", "flag": "🇸🇬", "id": "192", "prefix": "65"},
    "lk": {"title": "سريلانكا", "flag": "🇱🇰", "id": "44", "prefix": "94"},
    "srilanka": {"title": "سريلانكا", "flag": "🇱🇰", "id": "44", "prefix": "94"},
    "np": {"title": "نيبال", "flag": "🇳🇵", "id": "81", "prefix": "977"},
    "nepal": {"title": "نيبال", "flag": "🇳🇵", "id": "81", "prefix": "977"},
    "mm": {"title": "ميانمار (بورما)", "flag": "🇲🇲", "id": "5", "prefix": "95"},
    "myanmar": {"title": "ميانمار (بورما)", "flag": "🇲🇲", "id": "5", "prefix": "95"},
    "kh": {"title": "كمبوديا", "flag": "🇰🇭", "id": "24", "prefix": "855"},
    "cambodia": {"title": "كمبوديا", "flag": "🇰🇭", "id": "24", "prefix": "855"},
    "la": {"title": "لاوس", "flag": "🇱🇦", "id": "25", "prefix": "856"},
    "laos": {"title": "لاوس", "flag": "🇱🇦", "id": "25", "prefix": "856"},
    "bt": {"title": "بوتان", "flag": "🇧🇹", "id": "158", "prefix": "975"},
    "bhutan": {"title": "بوتان", "flag": "🇧🇹", "id": "158", "prefix": "975"},
    "mv": {"title": "جزر المالديف", "flag": "🇲🇻", "id": "159", "prefix": "960"},
    "maldives": {"title": "جزر المالديف", "flag": "🇲🇻", "id": "159", "prefix": "960"},
    "mn": {"title": "منغوليا", "flag": "🇲🇳", "id": "72", "prefix": "976"},
    "mongolia": {"title": "منغوليا", "flag": "🇲🇳", "id": "72", "prefix": "976"},
    "ng": {"title": "نيجيريا", "flag": "🇳🇬", "id": "17", "prefix": "234"},
    "nigeria": {"title": "نيجيريا", "flag": "🇳🇬", "id": "17", "prefix": "234"},
    "gh": {"title": "غانا", "flag": "🇬🇭", "id": "39", "prefix": "233"},
    "ghana": {"title": "غانا", "flag": "🇬🇭", "id": "39", "prefix": "233"},
    "ke": {"title": "كينيا", "flag": "🇰🇪", "id": "8", "prefix": "254"},
    "kenya": {"title": "كينيا", "flag": "🇰🇪", "id": "8", "prefix": "254"},
    "za": {"title": "جنوب إفريقيا", "flag": "🇿🇦", "id": "31", "prefix": "27"},
    "southafrica": {"title": "جنوب إفريقيا", "flag": "🇿🇦", "id": "31", "prefix": "27"},
    "ci": {"title": "ساحل العاج", "flag": "🇨🇮", "id": "27", "prefix": "225"},
    "ivorycoast": {"title": "ساحل العاج", "flag": "🇨🇮", "id": "27", "prefix": "225"},
    "sn": {"title": "السنغال", "flag": "🇸🇳", "id": "61", "prefix": "221"},
    "senegal": {"title": "السنغال", "flag": "🇸🇳", "id": "61", "prefix": "221"},
    "cm": {"title": "الكاميرون", "flag": "🇨🇲", "id": "41", "prefix": "237"},
    "cameroon": {"title": "الكاميرون", "flag": "🇨🇲", "id": "41", "prefix": "237"},
    "ao": {"title": "أنغولا", "flag": "🇦🇴", "id": "76", "prefix": "244"},
    "angola": {"title": "أنغولا", "flag": "🇦🇴", "id": "76", "prefix": "244"},
    "tz": {"title": "تنزانيا", "flag": "🇹🇿", "id": "9", "prefix": "255"},
    "tanzania": {"title": "تنزانيا", "flag": "🇹🇿", "id": "9", "prefix": "255"},
    "ug": {"title": "أوغندا", "flag": "🇺🇬", "id": "75", "prefix": "256"},
    "uganda": {"title": "أوغندا", "flag": "🇺🇬", "id": "75", "prefix": "256"},
    "et": {"title": "إثيوبيا", "flag": "🇪🇹", "id": "71", "prefix": "251"},
    "ethiopia": {"title": "إثيوبيا", "flag": "🇪🇹", "id": "71", "prefix": "251"},
    "mg": {"title": "مدغشقر", "flag": "🇲🇬", "id": "17", "prefix": "261"},
    "madagascar": {"title": "مدغشقر", "flag": "🇲🇬", "id": "17", "prefix": "261"},
    "mz": {"title": "موزمبيق", "flag": "🇲🇿", "id": "80", "prefix": "258"},
    "mozambique": {"title": "موزمبيق", "flag": "🇲🇿", "id": "80", "prefix": "258"},
    "zm": {"title": "زامبيا", "flag": "🇿🇲", "id": "147", "prefix": "260"},
    "zambia": {"title": "زامبيا", "flag": "🇿🇲", "id": "147", "prefix": "260"},
    "zw": {"title": "زيمبابوي", "flag": "🇿🇼", "id": "96", "prefix": "263"},
    "zimbabwe": {"title": "زيمبابوي", "flag": "🇿🇼", "id": "96", "prefix": "263"},
    "ne": {"title": "النيجر", "flag": "🇳🇪", "id": "128", "prefix": "227"},
    "niger": {"title": "النيجر", "flag": "🇳🇪", "id": "128", "prefix": "227"},
    "ml": {"title": "مالي", "flag": "🇲🇱", "id": "69", "prefix": "223"},
    "mali": {"title": "مالي", "flag": "🇲🇱", "id": "69", "prefix": "223"},
    "bf": {"title": "بوركينا فاسو", "flag": "🇧🇫", "id": "152", "prefix": "226"},
    "burkinafaso": {"title": "بوركينا فاسو", "flag": "🇧🇫", "id": "152", "prefix": "226"},
    "gn": {"title": "غينيا", "flag": "🇬🇳", "id": "66", "prefix": "224"},
    "guinea": {"title": "غينيا", "flag": "🇬🇳", "id": "66", "prefix": "224"},
    "bj": {"title": "بنين", "flag": "🇧🇯", "id": "125", "prefix": "229"},
    "benin": {"title": "بنين", "flag": "🇧🇯", "id": "125", "prefix": "229"},
    "tg": {"title": "توغو", "flag": "🇹🇬", "id": "99", "prefix": "228"},
    "togo": {"title": "توغو", "flag": "🇹🇬", "id": "99", "prefix": "228"},
    "td": {"title": "تشاد", "flag": "🇹🇩", "id": "42", "prefix": "235"},
    "chad": {"title": "تشاد", "flag": "🇹🇩", "id": "42", "prefix": "235"},
    "cg": {"title": "الكونغو", "flag": "🇨🇬", "id": "150", "prefix": "242"},
    "congo": {"title": "الكونغو", "flag": "🇨🇬", "id": "150", "prefix": "242"},
    "cd": {"title": "الكونغو الديمقراطية", "flag": "🇨🇩", "id": "151", "prefix": "243"},
    "drc": {"title": "الكونغو الديمقراطية", "flag": "🇨🇩", "id": "151", "prefix": "243"},
    "rw": {"title": "رواندا", "flag": "🇷🇼", "id": "140", "prefix": "250"},
    "rwanda": {"title": "رواندا", "flag": "🇷🇼", "id": "140", "prefix": "250"},
    "sl": {"title": "سيراليون", "flag": "🇸🇱", "id": "115", "prefix": "232"},
    "sierraleone": {"title": "سيراليون", "flag": "🇸🇱", "id": "115", "prefix": "232"},
    "lr": {"title": "ليبيريا", "flag": "🇱🇷", "id": "135", "prefix": "231"},
    "liberia": {"title": "ليبيريا", "flag": "🇱🇷", "id": "135", "prefix": "231"},
    "mw": {"title": "ملاوي", "flag": "🇲🇼", "id": "111", "prefix": "265"},
    "malawi": {"title": "ملاوي", "flag": "🇲🇼", "id": "111", "prefix": "265"},
    "bw": {"title": "بوتسوانا", "flag": "🇧🇼", "id": "123", "prefix": "267"},
    "botswana": {"title": "بوتسوانا", "flag": "🇧🇼", "id": "123", "prefix": "267"},
    "na": {"title": "ناميبيا", "flag": "🇳🇦", "id": "138", "prefix": "264"},
    "namibia": {"title": "ناميبيا", "flag": "🇳🇦", "id": "138", "prefix": "264"},
    "ls": {"title": "ليسوتو", "flag": "🇱🇸", "id": "136", "prefix": "266"},
    "lesotho": {"title": "ليسوتو", "flag": "🇱🇸", "id": "136", "prefix": "266"},
    "sz": {"title": "إسواتيني", "flag": "🇸🇿", "id": "144", "prefix": "268"},
    "eswatini": {"title": "إسواتيني", "flag": "🇸🇿", "id": "144", "prefix": "268"},
    "mu": {"title": "موريشيوس", "flag": "🇲🇺", "id": "157", "prefix": "230"},
    "mauritius": {"title": "موريشيوس", "flag": "🇲🇺", "id": "157", "prefix": "230"},
    "sc": {"title": "سيشل", "flag": "🇸🇨", "id": "184", "prefix": "248"},
    "seychelles": {"title": "سيشل", "flag": "🇸🇨", "id": "184", "prefix": "248"},
    "cv": {"title": "الرأس الأخضر", "flag": "🇨🇻", "id": "186", "prefix": "238"},
    "capeverde": {"title": "الرأس الأخضر", "flag": "🇨🇻", "id": "186", "prefix": "238"},
    "st": {"title": "ساو تومي وبرينسيب", "flag": "🇸🇹", "id": "178", "prefix": "239"},
    "saotome": {"title": "ساو تومي وبرينسيب", "flag": "🇸🇹", "id": "178", "prefix": "239"},
    "do": {"title": "الدومينيكان", "flag": "🇩🇴", "id": "109", "prefix": "1809"},
    "dominican": {"title": "الدومينيكان", "flag": "🇩🇴", "id": "109", "prefix": "1809"},
    "ht": {"title": "هايتي", "flag": "🇭🇹", "id": "26", "prefix": "509"},
    "haiti": {"title": "هايتي", "flag": "🇭🇹", "id": "26", "prefix": "509"},
    "cu": {"title": "كوبا", "flag": "🇨🇺", "id": "188", "prefix": "53"},
    "cuba": {"title": "كوبا", "flag": "🇨🇺", "id": "188", "prefix": "53"},
    "jm": {"title": "جامايكا", "flag": "🇯🇲", "id": "118", "prefix": "1876"},
    "jamaica": {"title": "جامايكا", "flag": "🇯🇲", "id": "118", "prefix": "1876"},
    "tt": {"title": "ترينيداد وتوباغو", "flag": "🇹🇹", "id": "104", "prefix": "1868"},
    "trinidad": {"title": "ترينيداد وتوباغو", "flag": "🇹🇹", "id": "104", "prefix": "1868"},
    "bs": {"title": "الباهاماس", "flag": "🇧🇸", "id": "224", "prefix": "1242"},
    "bahamas": {"title": "الباهاماس", "flag": "🇧🇸", "id": "224", "prefix": "1242"},
    "bb": {"title": "باربادوس", "flag": "🇧🇧", "id": "122", "prefix": "1246"},
    "barbados": {"title": "باربادوس", "flag": "🇧🇧", "id": "122", "prefix": "1246"},
    "lc": {"title": "سانت لوسيا", "flag": "🇱🇨", "id": "164", "prefix": "1758"},
    "stlucia": {"title": "سانت لوسيا", "flag": "🇱🇨", "id": "164", "prefix": "1758"},
    "vc": {"title": "سانت فينسنت", "flag": "🇻🇨", "id": "166", "prefix": "1784"},
    "grenadines": {"title": "سانت فينسنت", "flag": "🇻🇨", "id": "166", "prefix": "1784"},
    "gd": {"title": "غرينادا", "flag": "🇬🇩", "id": "127", "prefix": "1473"},
    "grenada": {"title": "غرينادا", "flag": "🇬🇩", "id": "127", "prefix": "1473"},
    "dm": {"title": "دومينيكا", "flag": "🇩🇲", "id": "126", "prefix": "1767"},
    "dominica": {"title": "دومينيكا", "flag": "🇩🇲", "id": "126", "prefix": "1767"},
    "bz": {"title": "بليز", "flag": "🇧🇿", "id": "124", "prefix": "501"},
    "belize": {"title": "بليز", "flag": "🇧🇿", "id": "124", "prefix": "501"},
    "gt": {"title": "غواتيمالا", "flag": "🇬🇹", "id": "92", "prefix": "502"},
    "guatemala": {"title": "غواتيمالا", "flag": "🇬🇹", "id": "92", "prefix": "502"},
    "hn": {"title": "هندوراس", "flag": "🇭🇳", "id": "88", "prefix": "504"},
    "honduras": {"title": "هندوراس", "flag": "🇭🇳", "id": "88", "prefix": "504"},
    "sv": {"title": "السلفادور", "flag": "🇸🇻", "id": "101", "prefix": "503"},
    "elsalvador": {"title": "السلفادور", "flag": "🇸🇻", "id": "101", "prefix": "503"},
    "ni": {"title": "نيكاراغوا", "flag": "🇳🇮", "id": "91", "prefix": "505"},
    "nicaragua": {"title": "نيكاراغوا", "flag": "🇳🇮", "id": "91", "prefix": "505"},
    "cr": {"title": "كوستاريكا", "flag": "🇨🇷", "id": "93", "prefix": "506"},
    "costarica": {"title": "كوستاريكا", "flag": "🇨🇷", "id": "93", "prefix": "506"},
    "pa": {"title": "بنما", "flag": "🇵🇦", "id": "112", "prefix": "507"},
    "panama": {"title": "بنما", "flag": "🇵🇦", "id": "112", "prefix": "507"},
    "py": {"title": "باراغواي", "flag": "🇵🇾", "id": "87", "prefix": "595"},
    "paraguay": {"title": "باراغواي", "flag": "🇵🇾", "id": "87", "prefix": "595"},
    "bo": {"title": "بوليفيا", "flag": "🇧🇴", "id": "85", "prefix": "591"},
    "bolivia": {"title": "بوليفيا", "flag": "🇧🇴", "id": "85", "prefix": "591"},
    "gy": {"title": "غيانا", "flag": "🇬🇾", "id": "131", "prefix": "592"},
    "guyana": {"title": "غيانا", "flag": "🇬🇾", "id": "131", "prefix": "592"},
    "sr": {"title": "سورينام", "flag": "🇸🇷", "id": "142", "prefix": "597"},
    "suriname": {"title": "سورينام", "flag": "🇸🇷", "id": "142", "prefix": "597"},
    "pg": {"title": "بابوا غينيا الجديدة", "flag": "🇵🇬", "id": "79", "prefix": "675"},
    "papua": {"title": "بابوا غينيا الجديدة", "flag": "🇵🇬", "id": "79", "prefix": "675"},
    "fj": {"title": "فيجي", "flag": "🇫🇯", "id": "189", "prefix": "679"},
    "fiji": {"title": "فيجي", "flag": "🇫🇯", "id": "189", "prefix": "679"},
    "tl": {"title": "تيمور الشرقية", "flag": "🇹🇱", "id": "194", "prefix": "670"},
    "timor": {"title": "تيمور الشرقية", "flag": "🇹🇱", "id": "194", "prefix": "670"},
    "ki": {"title": "كيريباتي", "flag": "🇰🇮", "id": "212", "prefix": "686"},
    "kiribati": {"title": "كيريباتي", "flag": "🇰🇮", "id": "212", "prefix": "686"},
    "pw": {"title": "بالاو", "flag": "🇵🇼", "id": "174", "prefix": "680"},
    "palau": {"title": "بالاو", "flag": "🇵🇼", "id": "174", "prefix": "680"},
    "to": {"title": "تونغا", "flag": "🇹🇴", "id": "196", "prefix": "676"},
    "tonga": {"title": "تونغا", "flag": "🇹🇴", "id": "196", "prefix": "676"},
    "ws": {"title": "ساموا", "flag": "🇼🇸", "id": "197", "prefix": "685"},
    "samoa": {"title": "ساموا", "flag": "🇼🇸", "id": "197", "prefix": "685"},
    "gu": {"title": "غوام", "flag": "🇬🇺", "id": "206", "prefix": "1671"},
    "guam": {"title": "غوام", "flag": "🇬🇺", "id": "206", "prefix": "1671"},
    "aw": {"title": "أروبا", "flag": "🇦🇼", "id": "179", "prefix": "297"},
    "aruba": {"title": "أروبا", "flag": "🇦🇼", "id": "179", "prefix": "297"},
    "pr": {"title": "بورتوريكو", "flag": "🇵🇷", "id": "97", "prefix": "1787"},
    "puertorico": {"title": "بورتوريكو", "flag": "🇵🇷", "id": "97", "prefix": "1787"},
    "si": {"title": "سلوفينيا", "flag": "🇸🇮", "id": "183", "prefix": "386"},
    "slovenia": {"title": "سلوفينيا", "flag": "🇸🇮", "id": "183", "prefix": "386"},
    "ag": {"title": "أنتيغوا وبربودا", "flag": "🇦🇬", "id": "169", "prefix": "1268"},
    "antiguaandbarbuda": {"title": "أنتيغوا وبربودا", "flag": "🇦🇬", "id": "169", "prefix": "1268"},
    "bi": {"title": "بوروندي", "flag": "🇧🇮", "id": "118", "prefix": "257"},
    "burundi": {"title": "بوروندي", "flag": "🇧🇮", "id": "118", "prefix": "257"},
    "gq": {"title": "غينيا الاستوائية", "flag": "🇬🇶", "id": "167", "prefix": "240"},
    "equatorialguinea": {"title": "غينيا الاستوائية", "flag": "🇬🇶", "id": "167", "prefix": "240"},
    "ga": {"title": "الغابون", "flag": "🇬🇦", "id": "154", "prefix": "241"},
    "gabon": {"title": "الغابون", "flag": "🇬🇦", "id": "154", "prefix": "241"},
    "gm": {"title": "غامبيا", "flag": "🇬🇲", "id": "121", "prefix": "220"},
    "gambia": {"title": "غامبيا", "flag": "🇬🇲", "id": "121", "prefix": "220"},
    "gp": {"title": "غوادلوب", "flag": "🇬🇵", "id": "125", "prefix": "590"},
    "guadeloupe": {"title": "غوادلوب", "flag": "🇬🇵", "id": "125", "prefix": "590"},
    "gw": {"title": "غينيا بيساو", "flag": "🇬🇼", "id": "130", "prefix": "245"},
    "guineabissau": {"title": "غينيا بيساو", "flag": "🇬🇼", "id": "130", "prefix": "245"},
    "lu": {"title": "لوكسمبورغ", "flag": "🇱🇺", "id": "165", "prefix": "352"},
    "luxembourg": {"title": "لوكسمبورغ", "flag": "🇱🇺", "id": "165", "prefix": "352"},
    "mo": {"title": "ماكاو", "flag": "🇲🇴", "id": "166", "prefix": "853"},
    "macau": {"title": "ماكاو", "flag": "🇲🇴", "id": "166", "prefix": "853"},
    "me": {"title": "الجبل الأسود", "flag": "🇲🇪", "id": "171", "prefix": "382"},
    "montenegro": {"title": "الجبل الأسود", "flag": "🇲🇪", "id": "171", "prefix": "382"},
    "nc": {"title": "كاليدونيا الجديدة", "flag": "🇳🇨", "id": "185", "prefix": "687"},
    "newcaledonia": {"title": "كاليدونيا الجديدة", "flag": "🇳🇨", "id": "185", "prefix": "687"},
    "mk": {"title": "مقدونيا الشمالية", "flag": "🇲🇰", "id": "184", "prefix": "389"},
    "northmacedonia": {"title": "مقدونيا الشمالية", "flag": "🇲🇰", "id": "184", "prefix": "389"},
    "re": {"title": "ريونيون", "flag": "🇷🇪", "id": "123", "prefix": "262"},
    "reunion": {"title": "ريونيون", "flag": "🇷🇪", "id": "123", "prefix": "262"},
    "kn": {"title": "سانت كيتس ونيفيس", "flag": "🇰🇳", "id": "134", "prefix": "1869"},
    "saintkittsandnevis": {"title": "سانت كيتس ونيفيس", "flag": "🇰🇳", "id": "134", "prefix": "1869"},
    "sk": {"title": "سلوفاكيا", "flag": "🇸🇰", "id": "182", "prefix": "421"},
    "slovakia": {"title": "سلوفاكيا", "flag": "🇸🇰", "id": "182", "prefix": "421"},
    "sb": {"title": "جزر سليمان", "flag": "🇸🇧", "id": "193", "prefix": "677"},
    "solomonislands": {"title": "جزر سليمان", "flag": "🇸🇧", "id": "193", "prefix": "677"},
    "bm": {"title": "برمودا", "flag": "🇧🇲", "id": "1003", "prefix": "1441"},
    "bermuda": {"title": "برمودا", "flag": "🇧🇲", "id": "1003", "prefix": "1441"},
    "vu": {"title": "فانواتو", "flag": "🇻🇺", "id": "1007", "prefix": "678"},
    "vanuatu": {"title": "فانواتو", "flag": "🇻🇺", "id": "1007", "prefix": "678"},
    "gl": {"title": "جرينلاند", "flag": "🇬🇱", "id": "1008", "prefix": "299"},
    "greenland": {"title": "جرينلاند", "flag": "🇬🇱", "id": "1008", "prefix": "299"},
    "mq": {"title": "مارتينيك", "flag": "🇲🇶", "id": "1011", "prefix": "596"},
    "martinique": {"title": "مارتينيك", "flag": "🇲🇶", "id": "1011", "prefix": "596"},
    "pf": {"title": "بولينيزيا الفرنسية", "flag": "🇵🇫", "id": "1012", "prefix": "689"},
    "frenchpolynesia": {"title": "بولينيزيا الفرنسية", "flag": "🇵🇫", "id": "1012", "prefix": "689"},
    "as": {"title": "ساموا الأمريكية", "flag": "🇦🇸", "id": "10161", "prefix": "1684"},
    "americansamoa": {"title": "ساموا الأمريكية", "flag": "🇦🇸", "id": "10161", "prefix": "1684"},
    "li": {"title": "ليختنشتاين", "flag": "🇱🇮", "id": "10348", "prefix": "423"},
    "liechtenstein": {"title": "ليختنشتاين", "flag": "🇱🇮", "id": "10348", "prefix": "423"},
    "sx": {"title": "سينت مارتن", "flag": "🇸🇽", "id": "10349", "prefix": "1721"},
    "sintmaarten": {"title": "سينت مارتن", "flag": "🇸🇽", "id": "10349", "prefix": "1721"},
    "kr": {"title": "كوريا الجنوبية", "flag": "🇰🇷", "id": "10350", "prefix": "82"},
    "southkorea": {"title": "كوريا الجنوبية", "flag": "🇰🇷", "id": "10350", "prefix": "82"},
    "ir": {"title": "إيران", "flag": "🇮🇷", "id": "10016", "prefix": "98"},
    "iran": {"title": "إيران", "flag": "🇮🇷", "id": "10016", "prefix": "98"}
}

# ==========================================
# كتالوج خدمات الرشق الاحترافية (نظام الملك)
# ==========================================
# ملاحظة: سعر العضو الأساسي من Plus SMM هو 0.000271$ (0.271$ لكل 1000)
# مع إضافة هامش الربح 30%:
# 0.000271 * 1.30 = 0.0003523$ لكل عضو (0.3523$ لكل 1000)

SMM_SERVICES = {
    "tg_king_members": {
        "id": "tg_king_members",
        "section": "رشق تيليجرام",
        "title": "متابعين تيليجرام | الأفضل | سرعة | ضمان 30ي",
        "raw_unit_price": 0.000271,     # سعر العضو من المزود بلاس
        "raw_per_1000": 0.271,          # سعر الـ 1000 من المزود
        "min_qty": 10,
        "max_qty": 1000000,
        "quality": "حسابات عالية الجودة الافضل",
        "speed": "سريعة برق (حتى 100 ألف متابع يوميًا)",
        "guarantee": "30 يوم",
        "refill": "نعم",
        "compensation": "نعم",
        "cancel_btn": "مُفعّل",
        "link_type": "رابط قناة أو مجموعة تيليجرام (مثال: https://t.me/NumbrWahm أو /NumbrWahm)",
        "desc": (
            "نظام الملك:\n"
            "ضمان وقت البدء فوري. الجودة حسابات عالية الجودة. "
            "السرعة: حتى 100 ألف متابع يوميًا. معدل السقوط: لا يوجد. "
            "إعادة التعبئة: نعم. التعويض: نعم. زر الإلغاء: مُفعّل. "
            "الرابط: رابط قناة أو مجموعة تيليجرام. "
            "ملاحظات: قد تختلف سرعة التنفيذ عند ارتفاع الضغط على الخدمة. "
            "لا تطلب الخدمة مرة أخرى على نفس الرابط حتى يكتمل الطلب الحالي. "
            "عند وجود أي مشكلة، تواصل مع الدعم."
        )
    },
    "tg_king_views": {
        "id": "tg_king_views",
        "section": "رشق تيليجرام",
        "title": "مشاهدات منشورات تيليجرام | فوري وسريع",
        "raw_unit_price": 0.00005,
        "raw_per_1000": 0.05,
        "min_qty": 50,
        "max_qty": 500000,
        "quality": "حسابات حقيقية متفاعلة",
        "speed": "فوري خلال دقائق",
        "guarantee": "دائم بدون نقص",
        "refill": "نعم",
        "compensation": "نعم",
        "cancel_btn": "مُفعّل",
        "link_type": "رابط منشور القناة (مثال: https://t.me/channel/123)",
        "desc": "مشاهدات سريعة وفورية للمنشورات لزيادة الثقة والتفاعل."
    },
    "ig_king_followers": {
        "id": "ig_king_followers",
        "section": "رشق إنستغرام",
        "title": "متابعين إنستغرام | ضمان 30 يوم VIP",
        "raw_unit_price": 0.00115,
        "raw_per_1000": 1.15,
        "min_qty": 50,
        "max_qty": 500000,
        "quality": "حسابات بصور ومنشورات",
        "speed": "20 ألف إلى 50 ألف يومياً",
        "guarantee": "30 يوم مع تعويض آلي",
        "refill": "نعم",
        "compensation": "نعم",
        "cancel_btn": "مُفعّل",
        "link_type": "رابط حساب الإنستغرام (يجب أن يكون عاماً وليس خاصاً)",
        "desc": "متابعين حسابات ممتازة لرفع مظهر حساب الإنستغرام."
    },
    "tk_king_followers": {
        "id": "tk_king_followers",
        "section": "رشق تيك توك",
        "title": "متابعين تيك توك | لفتح البث المباشر LIVE",
        "raw_unit_price": 0.00150,
        "raw_per_1000": 1.50,
        "min_qty": 50,
        "max_qty": 200000,
        "quality": "حسابات نشطة",
        "speed": "سريعة حتى 30 ألف يومياً",
        "guarantee": "ضمان 30 يوم",
        "refill": "نعم",
        "compensation": "نعم",
        "cancel_btn": "مُفعّل",
        "link_type": "رابط حساب تيك توك",
        "desc": "مثالي لفتح ميزة البث المباشر (LIVE) وزيادة الانتشار."
    },
    "pubg_60": {
        "id": "pubg_60",
        "section": "شحن ألعاب",
        "title": "🎮 شدات ببجي PUBG (60 UC)",
        "raw_unit_price": 0.85,
        "raw_per_1000": 850.0,
        "min_qty": 1,
        "max_qty": 100,
        "quality": "شحن رسمي ID",
        "speed": "خلال 5-15 دقيقة",
        "guarantee": "شحن رسمي معتمد",
        "refill": "غير منطبق",
        "compensation": "نعم",
        "cancel_btn": "مُفعّل قبل التنفيذ",
        "link_type": "الآيدي (Player ID) داخل لعبة ببجي",
        "desc": "شحن رسمي مباشر بالآيدي بدون كلمة سر."
    },
    "pubg_325": {
        "id": "pubg_325",
        "section": "شحن ألعاب",
        "title": "🎮 شدات ببجي PUBG (325 UC + هدية)",
        "raw_unit_price": 4.00,
        "raw_per_1000": 4000.0,
        "min_qty": 1,
        "max_qty": 50,
        "quality": "شحن رويال باس رسمي",
        "speed": "فوري بالآيدي",
        "guarantee": "شحن رسمي معتمد",
        "refill": "غير منطبق",
        "compensation": "نعم",
        "cancel_btn": "مُفعّل قبل التنفيذ",
        "link_type": "الآيدي (Player ID)",
        "desc": "شحن كافي للرويال باس والمواسم."
    }
}

# ==========================================
# قاعدة بيانات الدول الشاملة ومفاتيحها
# ==========================================

COUNTRIES = {
    "54": {"name": "yemen", "title": "اليمن", "flag": "🇾🇪", "prefix": "967", "default_rub": 35.0},
    "53": {"name": "saudi", "title": "السعودية", "flag": "🇸🇦", "prefix": "966", "default_rub": 40.0},
    "21": {"name": "egypt", "title": "مصر", "flag": "🇪🇬", "prefix": "20", "default_rub": 20.0},
    "73": {"name": "brazil", "title": "البرازيل", "flag": "🇧🇷", "prefix": "55", "default_rub": 30.0},
    "0": {"name": "russia", "title": "روسيا", "flag": "🇷🇺", "prefix": "7", "default_rub": 15.0},
    "187": {"name": "usa", "title": "أمريكا", "flag": "🇺🇸", "prefix": "1", "default_rub": 25.0},
    "16": {"name": "england", "title": "بريطانيا", "flag": "🇬🇧", "prefix": "44", "default_rub": 22.0},
    "6": {"name": "indonesia", "title": "إندونيسيا", "flag": "🇮🇩", "prefix": "62", "default_rub": 12.0},
    "2": {"name": "kazakhstan", "title": "كازاخستان", "flag": "🇰🇿", "prefix": "77", "default_rub": 18.0},
    "95": {"name": "uae", "title": "الإمارات", "flag": "🇦🇪", "prefix": "971", "default_rub": 40.0},
    "52": {"name": "iraq", "title": "العراق", "flag": "🇮🇶", "prefix": "964", "default_rub": 22.0},
    "116": {"name": "jordan", "title": "الأردن", "flag": "🇯🇴", "prefix": "962", "default_rub": 25.0},
    "117": {"name": "kuwait", "title": "الكويت", "flag": "🇰🇼", "prefix": "965", "default_rub": 38.0},
    "102": {"name": "morocco", "title": "المغرب", "flag": "🇲🇦", "prefix": "212", "default_rub": 20.0},
    "58": {"name": "algeria", "title": "الجزائر", "flag": "🇩🇿", "prefix": "213", "default_rub": 18.0},
    "89": {"name": "tunisia", "title": "تونس", "flag": "🇹🇳", "prefix": "216", "default_rub": 20.0},
    "148": {"name": "oman", "title": "عمان", "flag": "🇴🇲", "prefix": "968", "default_rub": 35.0},
    "145": {"name": "bahrain", "title": "البحرين", "flag": "🇧🇭", "prefix": "973", "default_rub": 35.0},
    "111": {"name": "qatar", "title": "قطر", "flag": "🇶🇦", "prefix": "974", "default_rub": 40.0},
    "110": {"name": "syria", "title": "سوريا", "flag": "🇸🇾", "prefix": "963", "default_rub": 28.0},
    "107": {"name": "lebanon", "title": "لبنان", "flag": "🇱🇧", "prefix": "961", "default_rub": 26.0},
    "114": {"name": "sudan", "title": "السودان", "flag": "🇸🇩", "prefix": "249", "default_rub": 20.0},
    "108": {"name": "libya", "title": "ليبيا", "flag": "🇱🇾", "prefix": "218", "default_rub": 24.0},
    "146": {"name": "palestine", "title": "فلسطين", "flag": "🇵🇸", "prefix": "970", "default_rub": 30.0},
    "22": {"name": "india", "title": "الهند", "flag": "🇮🇳", "prefix": "91", "default_rub": 10.0},
    "15": {"name": "poland", "title": "بولندا", "flag": "🇵🇱", "prefix": "48", "default_rub": 22.0},
    "36": {"name": "canada", "title": "كندا", "flag": "🇨🇦", "prefix": "1", "default_rub": 28.0},
    "56": {"name": "spain", "title": "إسبانيا", "flag": "🇪🇸", "prefix": "34", "default_rub": 25.0},
    "32": {"name": "romania", "title": "رومانيا", "flag": "🇷🇴", "prefix": "40", "default_rub": 18.0},
    "48": {"name": "netherlands", "title": "هولندا", "flag": "🇳🇱", "prefix": "31", "default_rub": 30.0},
    "13": {"name": "germany", "title": "ألمانيا", "flag": "🇩🇪", "prefix": "49", "default_rub": 32.0},
    "86": {"name": "italy", "title": "إيطاليا", "flag": "🇮🇹", "prefix": "39", "default_rub": 28.0},
    "78": {"name": "france", "title": "فرنسا", "flag": "🇫🇷", "prefix": "33", "default_rub": 30.0},
    "60": {"name": "turkey", "title": "تركيا", "flag": "🇹🇷", "prefix": "90", "default_rub": 24.0},
    "1": {"name": "ukraine", "title": "أوكرانيا", "flag": "🇺🇦", "prefix": "380", "default_rub": 16.0},
    "4": {"name": "philippines", "title": "الفلبين", "flag": "🇵🇭", "prefix": "63", "default_rub": 14.0},
    "5": {"name": "myanmar", "title": "ميانمار", "flag": "🇲🇲", "prefix": "95", "default_rub": 12.0},
    "7": {"name": "malaysia", "title": "ماليزيا", "flag": "🇲🇾", "prefix": "60", "default_rub": 18.0},
    "10": {"name": "vietnam", "title": "فيتنام", "flag": "🇻🇳", "prefix": "84", "default_rub": 14.0},
    "11": {"name": "kyrgyzstan", "title": "قيرغيزستان", "flag": "🇰🇬", "prefix": "996", "default_rub": 16.0},
    "17": {"name": "nigeria", "title": "نيجيريا", "flag": "🇳🇬", "prefix": "234", "default_rub": 12.0},
    "19": {"name": "uzbekistan", "title": "أوزبكستان", "flag": "🇺🇿", "prefix": "998", "default_rub": 18.0},
    "24": {"name": "cambodia", "title": "كمبوديا", "flag": "🇰🇭", "prefix": "855", "default_rub": 14.0},
    "31": {"name": "southafrica", "title": "جنوب إفريقيا", "flag": "🇿🇦", "prefix": "27", "default_rub": 18.0},
    "33": {"name": "colombia", "title": "كولومبيا", "flag": "🇨🇴", "prefix": "57", "default_rub": 18.0},
    "38": {"name": "pakistan", "title": "باكستان", "flag": "🇵🇰", "prefix": "92", "default_rub": 14.0},
    "40": {"name": "bangladesh", "title": "بنغلاديش", "flag": "🇧🇩", "prefix": "880", "default_rub": 12.0},
    "43": {"name": "czech", "title": "التشيك", "flag": "🇨🇿", "prefix": "420", "default_rub": 22.0},
    "44": {"name": "srilanka", "title": "سريلانكا", "flag": "🇱🇰", "prefix": "94", "default_rub": 14.0},
    "46": {"name": "sweden", "title": "السويد", "flag": "🇸🇪", "prefix": "46", "default_rub": 30.0},
    "51": {"name": "thailand", "title": "تايلاند", "flag": "🇹🇭", "prefix": "66", "default_rub": 16.0},
    "55": {"name": "mexico", "title": "المكسيك", "flag": "🇲🇽", "prefix": "52", "default_rub": 24.0},
    "62": {"name": "peru", "title": "بيرو", "flag": "🇵🇪", "prefix": "51", "default_rub": 18.0},
    "67": {"name": "argentina", "title": "الأرجنتين", "flag": "🇦🇷", "prefix": "54", "default_rub": 20.0},
    "77": {"name": "austria", "title": "النمسا", "flag": "🇦🇹", "prefix": "43", "default_rub": 30.0},
    "80": {"name": "switzerland", "title": "سويسرا", "flag": "🇨🇭", "prefix": "41", "default_rub": 35.0},
    "82": {"name": "belgium", "title": "بلجيكا", "flag": "🇧🇪", "prefix": "32", "default_rub": 28.0},
    "83": {"name": "bulgaria", "title": "بلغاريا", "flag": "🇧🇬", "prefix": "359", "default_rub": 18.0},
    "84": {"name": "hungary", "title": "المجر", "flag": "🇭🇺", "prefix": "36", "default_rub": 20.0},
    "87": {"name": "chile", "title": "تشيلي", "flag": "🇨🇱", "prefix": "56", "default_rub": 22.0},
    "90": {"name": "portugal", "title": "البرتغال", "flag": "🇵🇹", "prefix": "351", "default_rub": 26.0},
    "94": {"name": "georgia", "title": "جورجيا", "flag": "🇬🇪", "prefix": "995", "default_rub": 18.0},
    "100": {"name": "greece", "title": "اليونان", "flag": "🇬🇷", "prefix": "30", "default_rub": 26.0}
}